name: CI
on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued. But do not cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-sashboard:
    name: "Deploy data.tira.io to GitHub Pages"
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4     
      - name: 🧰 Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: 🧰 Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: 🧰 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 🏗️ Build the web app
        run: make
      - name: 📤 Upload web app artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: data/dist/
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
